[project]
name = "b-tech-it"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
<<<<<<< HEAD
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.8.4",
]
=======
requires-python = ">=3.13"
dependencies = []
>>>>>>> 16177b9fb6eeb3c0cfdb8488afcd72c9e77f846a
